### ISSUE TITLE
How to see the demo work?

### ISSUE THREAD

**Issue by curran** [internetofelephants/trajvis#1]
I'm interested in seeing what this software does.

https://internetofelephants.github.io/trajvis/

![image](https://user-images.githubusercontent.com/68416/128051957-9d0c2798-c795-4509-8faf-72624e3d43f0.png)

However, I do not have a data file to upload. Is there an example data file that is available? Thanks!

**Comment by curran** [comment]
From DVS Slack:
>you could also try getting data from Movebank

https://www.movebank.org/cms/movebank-main

**Comment by raffmares** [comment]
New version (1.1.0) with sample data now available in the app's repository. Link provided in README and app:
![trajVis_screenshot](https://user-images.githubusercontent.com/19781562/135644581-9ecc8562-ffc3-4613-93f2-09f1ba9b7487.png)
